conf/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rolls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

rolls/urls.py
"""
Rolls app urls
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views

app_name = 'rolls'

urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('detail/<int:awesome>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
]

rolls/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Roll(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=255)
    year_made = models.IntegerField(default=1923)
    image = models.URLField()

rolls/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, ListView
from django.contrib.auth import get_user_model, login, authenticate

from .models import Roll


User = get_user_model()


class HomeView(TemplateView):
    template_name = 'rolls/list.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            ctx['rolls'] = Roll.objects.filter(user=self.request.user)

        return ctx


class RollListView(ListView):
    template_name = 'rolls/list.html'
    model = Roll

    def get_queryset(self, **kwargs):
        query_set = super().get_queryset(**kwargs)  # Roll.objects.all()

        user_id = self.kwargs.get('pk')

        query_set = query_set.filter(user_id=user_id)

        return query_set



class DetailView(TemplateView):
    template_name = 'rolls/detail.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        roll_id = self.kwargs['awesome']

        ctx['roll'] = Roll.objects.get(pk=roll_id)

        return ctx


# Create your views here.
class CreateView(TemplateView):
    template_name = 'rolls/create.html'

    def post(self, request, *args, **kwargs):
        title = self.request.POST.get('title')
        year_made = self.request.POST.get('year_made')

        roll = Roll()
        roll.title = title
        roll.year_made = year_made
        roll.user = self.request.user
        roll.save()

        return HttpResponseRedirect(reverse('rolls:index'))


# Create your views here.
class SignupView(TemplateView):
    template_name = 'registration/signup.html'

    def post(self, request, *args, **kwargs):
        # sign up user
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')
        password2 = self.request.POST.get('password2')

        # If the password fields don't match send the user back
        if password != password2:
            return HttpResponseRedirect(reverse('rolls:signup'))

        # If the username already exists, send the user back
        user = User.objects.filter(username=username)

        if user.count() > 0:
            return HttpResponseRedirect(reverse('rolls:signup'))

        # save user database record using fancy hashing on password
        User.objects.create_user(username=username, password=password)

        # Authenticate the user checks provided password against the hash
        user = authenticate(username=username, password=password)

        # Login the user (does the session table/cookie stuff)
        login(self.request, user)

        return HttpResponseRedirect(reverse('rolls:index'))

rolls/templates/rolls/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Player Piano Rolls</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>

    <div class="container">
        <div class="jumbotron">
            <h1>Player Piano Roll Tracker</h1>
        </div>

        {% block content %}{% endblock content %}
    </div>

</body>
</html>

rolls/templates/rolls/create.html
{% extends 'rolls/base.html' %}


{% block content %}

    <h2>Add a Roll to Your Library</h2>

    <form method="post" action="{% url 'rolls:create' %}">
        {% csrf_token %}
        <table>
        <tr>
            <td>Title</td>
            <td><input type="text" name="title"/></td>
        </tr>
        <tr>
            <td>Year Made</td>
            <td><input type="text" name="year_made"></td>
        </tr>
        </table>

        <input type="submit" value="Add Roll">
    </form>

{% endblock content %}

rolls/templates/rolls/detail.html
{% extends 'rolls/base.html' %}

{% block content %}

    <div class="row">
        <div class="col">

            <h1>{{ roll.title }}</h1>

            <p>
                <img src="{{ roll.image }}"/>
            </p>

        </div>
    </div>

{% endblock content %}

rolls/templates/rolls/list.html
{% extends 'rolls/base.html' %}

{% block content %}

    <div class="row">
        <div class="col">

            {% if not user.is_authenticated %}
                <div class="alert alert-danger" role="alert">
                    Hey! If you want to track your rolls <a href="{% url 'login' %}">please login</a>!
                </div>

            {% else %}
                <h3>Hi {{ user.username }}!</h3>

                <p class="float-right"><a href="{% url 'rolls:create' %}">Add</a></p>

                <ul clss="list-group">
                {% for roll in rolls %}
                    <li><a href="{% url 'rolls:detail' roll.id %}">{{ roll.title }} -- {{ roll.year_made }}</a></li>
                {% endfor %}
                </ul>
            {% endif %}

        </div>
    </div>

{% endblock content %}